
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dodqyhyxangsllxfkbkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZHF5aHl4YW5nc2xseGZrYmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTc2NTcsImV4cCI6MjA1ODQ3MzY1N30.XQjyXojW3cpBotOgozL7eJS4ZOpYwKyKPqkUzu_ITi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
